title: haungtengxiao
description: Windows 10 Developer
author: haungtengxiao
post_author: 黄腾霄
logo: /foo/static/img/avatar.png
github: https://github.com/haungtengxiao
about: Windows 10 Developer

baseurl: "/weibo"
url: "https://haungtengxiao.gitee.io"

allowsearch: trues

analytics:
  google: UA-108101550-1
disqus:
  name: haungtengxiao

share:
  twitter_username: haungtengxiao_gd


enableTags: true
tagarray: []

excerpt_separator: "<!--more-->"
paginate: 15
per_page: 15
paginate_path: "/blog/page:num/"
markdown: kramdown
gems: [jekyll-paginate, jekyll-gist]

# Content Collection
collections:
  articles:
    output: true

# Content Template
defaults:
  - scope:
      path: "_posts"
      type: "posts"
    values:
      layout: "post"
      author: "黄腾霄"
      permalink: "/post/:title.html"
  - scope:
      path: "_articles"
      type: "articles"
    values:
      layout: "post"
      author: "黄腾霄"
      permalink: "/article/:title.html"
