title: huangtengxiao
description: Windows Developer
author: huangtengxiao
post_author: 黄腾霄
logo: /static/img/avatar.png
github: https://github.com/xinyuehtx
about: Windows Developer

baseurl: ""
url: "https://xinyuehtx.github.io"

allowsearch: trues

analytics:
  google: 
disqus:
  name: huangtengxiao

share:
  twitter_username: 


enableTags: true
tagarray: []

excerpt_separator: "-----"
paginate: 15
per_page: 15
paginate_path: "/blog/page:num/"
markdown: kramdown
gems: [jekyll-paginate, jekyll-gist]

# Content Collection
collections:
  articles:
    output: true

# Content Template
defaults:
  - scope:
      path: "_posts"
      type: "posts"
    values:
      layout: "post"
      author: "黄腾霄"
      permalink: "/post/:title.html"
  - scope:
      path: "_articles"
      type: "articles"
    values:
      layout: "post"
      author: "黄腾霄"
      permalink: "/article/:title.html"

theme: jekyll-theme-merlot